Store/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from warehouse.views import purchases, purchase, purchase_product_delete, purchase_product, purchase_delete, acceptance, acceptances, return_view, returns, writeoff
from catalog.views import suppliers
from catalog.ajax import supplier, supplier_save, supplier_delete

from warehouse.ajax import purchase_save, get_product_price

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    (r'^purchases/page/(?P<page_pk>\d+)/$', purchases),
    (r'^purchase/$', purchase, {'id_purchase': 0}),
    (r'^purchase/(?P<id_purchase>\d+)/$', purchase),
    (r'^purchase/(?P<id_purchase>\d+)/product/(?P<id_product>\d+)/$', purchase_product),
    (r'^purchase/product/(?P<id_product>\d+)/delete/$', purchase_product_delete),
    (r'^purchase/(?P<id_purchase>\d+)/delete/$', purchase_delete),

    (r'^ajax/purchase/save/$', purchase_save),
    (r'^ajax/purchase/get_product_price/$', get_product_price),

    (r'^purchase/(?P<id_purchase>\d+)/acceptance/$', acceptance),
    (r'^acceptances/page/(?P<page_pk>\d+)/$', acceptances),

    (r'^acceptance/(?P<id_acceptance>\d+)/return/$', return_view),
    (r'^returns/page/(?P<page_pk>\d+)/$', returns),

    (r'^writeoff/$', writeoff, {'id_writeoff': 0}),

    (r'^suppliers/$', suppliers),
    (r'^ajax/supplier/$', supplier),
    (r'^ajax/supplier/save$', supplier_save),
    (r'^ajax/supplier/delete$', supplier_delete),
)

database/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime


class Supplier(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование')
    address = models.CharField(max_length=255, verbose_name='Адрес', blank=True)
    phone = models.CharField(max_length=255, verbose_name='Телефон', blank=True)
    contact = models.CharField(max_length=255, verbose_name='Контактное лицо, ФИО', blank=True)
    contact_phone = models.CharField(max_length=255, verbose_name='Контактное лицо, телефон', blank=True)
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    contact_comment = models.TextField(verbose_name='Контактное лицо, комментарий', blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'store_supplier'
        ordering = ['name']
        verbose_name_plural = u'Поставщики'
        verbose_name = u'Поставщик'

class CategoryOfProduct(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    parent = models.ForeignKey('self', verbose_name='Родитель', blank=True, null=True)

    def __unicode__(self):
        return '%s' % self.name

    class Meta:
        db_table = 'store_product_categories'
        ordering = ['name']
        verbose_name_plural = u'Категории товара'
        verbose_name = u'Категория товара'

class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    category = models.ForeignKey(CategoryOfProduct, verbose_name='Категория')
    measure_unit = models.CharField(max_length=255, verbose_name='Единица измерения')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Закупочная цена')
    supplier = models.ForeignKey(Supplier, blank=True, null=True, verbose_name='Поставщик')
    description = models.TextField(verbose_name='Описание', blank=True)

    def __unicode__(self):
        return '%s' % self.name

    class Meta:
        db_table = 'store_products'
        ordering = ['name']
        verbose_name_plural = u'Товары'
        verbose_name = u'Товар'

class Warehouse(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    address = models.CharField(max_length=255, verbose_name='Адрес', blank=True)
    comment = models.TextField(verbose_name='Комментарий', blank=True)

    def __unicode__(self):
        return '%s' % self.name

    class Meta:
        db_table = 'store_warehouses'
        ordering = ['name']
        verbose_name_plural = u'Склады'
        verbose_name = u'Склад'

class CategoryOfDish(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    parent = models.ForeignKey('self', verbose_name='Категория')
    archive = models.BooleanField(verbose_name='Признак архива')

    def __unicode__(self):
        return '%s' % self.name

    class Meta:
        db_table = 'store_dish_categories'
        ordering = ['name']
        verbose_name_plural = u'Категории калькуляционных карт'
        verbose_name = u'Категория калькуляционных карт'

class Dish(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    category = models.ForeignKey(CategoryOfDish, verbose_name='Категория')
    date_start = models.DateField(verbose_name='Действует с')
    date_end = models.DateField(verbose_name='Действует по', blank=True, null=True)
    portion = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Порция')
    master = models.BooleanField(verbose_name='выдан мастером или нет')
    created = models.DateTimeField(verbose_name='Дата создания')
    author = models.ForeignKey(User, verbose_name='Автор', related_name='dish_author')
    modified_date = models.DateTimeField(verbose_name='Дата изменения')
    modified_author = models.ForeignKey(User, verbose_name='Последний сотрудник внесший изменения ', related_name='dish_modified_author')
    comment = models.TextField(verbose_name='Комментарий', blank=True)


    def __unicode__(self):
        return '%s' % self.name

    class Meta:
        db_table = 'store_dishes'
        ordering = ['name']
        verbose_name_plural = u'Калькуляционные карты'
        verbose_name = u'Калькуляционная карта'

class ProductOfDish(models.Model):
    dish = models.ForeignKey(Dish, verbose_name='КК')
    product = models.ForeignKey(Product, verbose_name='Товар')
    measure_unit = models.CharField(max_length=255, verbose_name='Единица измерения')

    def __unicode__(self):
        return '%s' % self.product.name

    class Meta:
        db_table = 'store_dish_products'
        ordering = ['product']
        verbose_name_plural = u'Товары КК'
        verbose_name = u'Товар КК'


class SalePoint(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    warehouse = models.ForeignKey(Warehouse, verbose_name='Склад')
    address = models.CharField(max_length=255, verbose_name='Адрес', blank=True)
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    created = models.DateField(verbose_name='Дата создания')
    author = models.ForeignKey(User, verbose_name='Автор', related_name='point_author')
    modified_date = models.DateField(verbose_name='Дата изменения')
    modified_author = models.ForeignKey(User, verbose_name='Автор изменений', related_name='point_modified_author')

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'sale_salepoints'
        ordering = ['name']
        verbose_name_plural = u'Точки продаж'
        verbose_name = u'Точка продаж'

class Change(models.Model):
    point = models.ForeignKey(SalePoint, verbose_name='Точка продаж')
    cashier = models.ForeignKey(User, verbose_name='Кассир')
    start = models.DateField(verbose_name='Дата открытия')
    end = models.DateField(verbose_name='Дата закрытия', blank=True, null=True)

    def __unicode__(self):
        return self.point

    class Meta:
        db_table = 'sale_changes'
        ordering = ['point']
        verbose_name_plural = u'Смены'
        verbose_name = u'Смена'

class Sale(models.Model):
    point = models.ForeignKey(SalePoint, verbose_name='Точка продаж')
    cashier = models.ForeignKey(User, verbose_name='Кассир')
    change = models.ForeignKey(Change, verbose_name='Смена')
    discount = models.PositiveIntegerField(verbose_name='Скидка', blank=True, null=True)

    def __unicode__(self):
        return self.point

    class Meta:
        db_table = 'sale_sales'
        ordering = ['point']
        verbose_name_plural = u'Смены'
        verbose_name = u'Смена'

class DishOfSale(models.Model):
    sale = models.ForeignKey(Sale, verbose_name='Продажи')
    dish = models.ForeignKey(Dish, verbose_name='Блюда')
    amount = models.PositiveIntegerField(verbose_name='Количество')
    price = models.PositiveIntegerField(verbose_name='Цена')

    def __unicode__(self):
        return self.dish

    class Meta:
        db_table = 'sale_sale_dishes'
        ordering = ['dish']
        verbose_name_plural = u'Блюда для продажи'
        verbose_name = u'Блюдо для продажи'

class Purchase(models.Model):
    purchaser = models.ForeignKey(User, verbose_name='Закупщик', related_name='purchaser')
    supplier = models.ForeignKey(Supplier, verbose_name='Контрагент', blank=True, null=True)
    warehouse = models.ForeignKey(Warehouse, verbose_name='Склад')
    date_purchase = models.DateField(verbose_name='Дата закупа')
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    created = models.DateTimeField(verbose_name='Время создания')
    issued = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Выдано', blank=True, null=True)
    author = models.ForeignKey(User, verbose_name='Автор', related_name='purchase_author')
    modified_date = models.DateTimeField(verbose_name='Дата изменения')
    modified_author = models.ForeignKey(User, verbose_name='Автор изменения', related_name='purchase_modified_author')

    def __unicode__(self):
        return '#%s - %s' % (str(self.pk),str(self.date_purchase))

    class Meta:
        db_table = 'wr_purchases'
        ordering = ['pk']
        verbose_name_plural = u'Закупы'
        verbose_name = u'Закуп'

class ProductOfPurchase(models.Model):
    purchase = models.ForeignKey(Purchase, verbose_name='Закуп')
    product = models.ForeignKey(Product, verbose_name='Товары')
    purchase_amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Количество, закуп')
    acceptance_amount = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Количество, приемка', blank=True, null=True)
    return_amount = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Количество, возврат', blank=True, null=True)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Цена закупа')
    acceptance_price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Цена закупа', blank=True, null=True)
    return_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена закупа', blank=True, null=True)

    def __unicode__(self):
        return '%s' % self.product.name

    class Meta:
        db_table = 'wr_purchase_products'
        ordering = ['product']
        verbose_name_plural = u'Товары закупа'
        verbose_name = u'Товар закупа'

class Acceptance(models.Model):
    purchase = models.OneToOneField(Purchase, verbose_name='Закуп')
    date = models.DateField(verbose_name='Дата приемки')
    costs = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Расходы', blank=True, null=True)
    cash = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='В кассу')
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    created = models.DateTimeField(verbose_name='Время создания')

warehouse/forms.py
from django.forms import ModelForm
from django.forms.widgets import Textarea, Select
from database.models import Purchase, ProductOfPurchase, Acceptance, ReturnModel, WriteOff, ProductAtWarehouse, DishOfWarehouse
from django import forms

__author__ = 'Ars'


class PurchaseForm(ModelForm):
    class Meta:
        model = Purchase
        exclude = ('author', 'created', 'modified_date', 'modified_author')
        widgets = {
            'comment': Textarea(attrs={'rows': '5', 'cols': '3'})
        }


class ProductOfPurchaseForm(ModelForm):
    purchase_amount = forms.DecimalField(max_digits=10, decimal_places=2, min_value=0)

    class Meta:
        model = ProductOfPurchase
        exclude = ('purchase')
        widgets = {
            'product': Select(attrs={'style': 'width:220px;'}),
        }


class AcceptanceForm(ModelForm):
    class Meta:
        model = Acceptance
        exclude = ('author', 'created', 'modified_date', 'modified_author', 'purchase')
        widgets = {
            'comment': Textarea(attrs={'rows': '5', 'cols': '3'}),
        }


class ReturnForm(ModelForm):
    class Meta:
        model = ReturnModel
        exclude = ('author', 'created', 'modified_date', 'modified_author', 'acceptance')
        widgets = {
            'comment': Textarea(attrs={'rows': '5', 'cols': '3'}),
        }


class WriteOffForm(ModelForm):
    class Meta:
        model = WriteOff
        exclude = ('author', 'created', 'modified_date', 'modified_author')
        widgets = {
            'comment': Textarea(attrs={'rows': '5', 'cols': '3'})
        }


class ProductAtWarehouseForm(ModelForm):
    class Meta:
        model = ProductAtWarehouse
        widgets = {
            'product': Select(attrs={'style': 'width:220px;'}),
        }


class DishOfWarehouseForm(ModelForm):
    class Meta:
        model = DishOfWarehouse
        widgets = {
            'dish': Select(attrs={'style': 'width:220px;'}),
        }

templates/warehouse/writeoff.html
{% extends 'root.html' %}
{% block title %}Списание{% endblock %}
{% block content %}
    <div class="row-fluid">
        <form class=" no-margin" method="POST">
            <div class="span4">
                <div class="widget">
                    <div class="widget-header">
                        <div class="title">
                            Списание
                        </div>
                    <span class="tools">
                      <a class="fs1" aria-hidden="true" data-icon="&#xe090;"></a>
                    </span>
                    </div>
                    <div class="widget-body">
                        {% csrf_token %}
                        {{ form_writeoff.errors }}
                        <div class="control-group">
                            <label class="control-label" for="name">
                                Склад
                            </label>
                            <div class="controls controls-row">
                                {{ form_writeoff.warehouse }}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="name">
                                Причина
                            </label>
                            <div class="controls controls-row">
                                {{ form_writeoff.reason }}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="name">
                                Дата
                            </label>
                            <div class="controls controls-row">
                                {{ form_writeoff.date }}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="name">
                                Комментарий
                            </label>
                            <div class="controls controls-row">
                                {{ form_writeoff.comment }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="widget">
                    <div class="widget-header">
                        <div class="title">
                            Выбор блюда
                        </div>
                    <span class="tools">
                      <a class="fs1" aria-hidden="true" data-icon="&#xe090;"></a>
                    </span>
                    </div>
                    <div class="widget-body">
                        {{ form_dish.errors }}
                        <div class="control-group">
                            <label class="control-label" for="name">
                                Блюдо
                            </label>
                            <div class="controls controls-row">
                                {{ form_dish.dish }}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="name">
                                Количество
                            </label>
                            <div class="controls controls-row">
                                {{ form_dish.amount }}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="name">
                                Цена
                            </label>
                            <div class="controls controls-row">
                                {{ form_dish.price }}
                            </div>
                        </div>
                        <div class="form-actions">
                                <button type="submit" class="btn btn-info pull-right" id="add_product">
                                    Добавить блюдо
                                </button>
                            <div class="clearfix">
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="widget">
                    <div class="widget-header">
                        <div class="title">
                            Выбор товара
                        </div>
                    <span class="tools">
                      <a class="fs1" aria-hidden="true" data-icon="&#xe090;"></a>
                    </span>
                    </div>
                    <div class="widget-body">
                        {{ form_product.errors }}
                        <div class="control-group">
                            <label class="control-label" for="name">
                                Товар
                            </label>
                            <div class="controls controls-row">
                                {{ form_product.product }}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="name">
                                Количество
                            </label>
                            <div class="controls controls-row">
                                {{ form_product.amount }}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="name">
                                Цена
                            </label>
                            <div class="controls controls-row">
                                {{ form_product.price }}
                            </div>
                        </div>
                        <div class="form-actions">
                                <button type="submit" class="btn btn-info pull-right" id="add_product">
                                    Добавить товар
                                </button>
                            <div class="clearfix">
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="row-fluid">
        <div class="span12">
            <div class="widget">
                <div class="widget-header">
                    <div class="title">
                        Товары
                    </div>
                    <span class="tools">
                      <a class="fs1" aria-hidden="true" data-icon="&#xe090;"></a>
                    </span>
                </div>
                <div class="widget-body">
                    <table class="table table-condensed table-striped table-bordered table-hover no-margin">
                        <thead>
                        <tr>
                            <th style="width:5%">
                            </th>
                            <th style="width:15%">
                                Товар/Блюдо
                            </th>
                            <th style="width:15%" class="hidden-phone">
                                Количество
                            </th>
                            <th style="width:15%" class="hidden-phone">
                                Остаток
                            </th>
                            <th style="width:10%" class="hidden-phone">
                                Цена
                            </th>
                            <th style="width:25%" class="hidden-phone">
                                Сумма
                            </th>
                            <th style="width:10%" class="hidden-phone">
                                Действия
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product in products %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td class="hidden-phone">{{ product.0.product }}</td>
                                <td><span class="name">{{ product.0.purchase_amount }}</span></td>
                                <td><span class="name">{{ product.0.product.measure_unit }}</span></td>
                                <td class="hidden-phone">{{ product.0.purchase_price }}</td>
                                <td class="hidden-phone">{{ product.1 }}</td>
                                <td>
                                    {% if purchase.acceptance == None  or purchase.acceptance == ''%}
                                        <div class="tools">
                                            <div class="btn-group">
                                                <a class="btn btn-small" data-original-title="" href="/purchase/{{ id_purchase }}/product/{{ product.0.pk }}/">
                                                    <i class="icon-edit" data-original-title="Редактировать">
                                                    </i>
                                                </a>
                                                <a class="btn btn-small delete" data-original-title="" href="/purchase/product/{{ product.0.pk }}/delete/">
                                                    <i class="icon-trash" data-original-title="Удалить">
                                                    </i>
                                                </a>
                                            </div>
                                        </div>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Итого</strong></td>
                            <td><strong>{{ total }}</strong></td>
                            <td></td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="form-actions no-margin">
                        {% if id_purchase != 0 %}
                            {% if purchase.acceptance == None or purchase.acceptance == '' %}
                                <a class="button btn btn-info pull-left" href="/purchase/{{ id_purchase }}/delete/" id="delete_purchase">
                                    Удалить закуп
                                </a>
                            {% endif %}
                        {% endif %}
                        {% if purchase.acceptance == None  or purchase.acceptance == '' %}
                            <button type="button" class="btn btn-info pull-right" id="create">
                                Сохранить
                            </button>
                        {% endif %}
                        <div class="clearfix">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="/media/theme/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="/media/store/js/purchase.js"></script>
    <script type="text/javascript" src="/media/theme/js/select2.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#id_date').datepicker({
                format: 'yyyy-mm-dd'
            });
            $('#id_product').select2();
            $('#id_dish').select2();
            $.fn.purchase();
            $('a').tooltip('hide');
            $('i').tooltip('hide');
        });
    </script>
{% endblock %}
{% block css %}
    <link href="/media/theme/css/datepicker.css" rel="stylesheet">
    <link href="/media/theme/css/select2.css" rel="stylesheet">
{% endblock %}